Review16 07 2020
haevg-rz/TrustCenterSearchGui pull request #143
Opened 2020-07-16 14:55 UTC by KaHBrat

2020-07-16 16:20 UTC, TobiasMeissner2000 commented on TrustCenterSearch.Presentation/ViewModel.cs
> +            foreach (var trustCenterHistoryName in Core.GetTrustCenterHistory())
this.

2020-07-16 16:20 UTC, TobiasMeissner2000 commented on TrustCenterSearch.Presentation/ViewModel.cs
> +                TrustCenterHistoryActive.Add(trustCenterHistoryName);
this.

2020-07-16 16:21 UTC, TobiasMeissner2000 commented on TrustCenterSearch.Presentation/ViewModel.cs
> +            return certificateAttributes.Any(atr => atr.Contains(SearchBarInput.ToLower()));
this.

2020-07-16 16:24 UTC, TobiasMeissner2000 requested changes
three missing this.

2020-07-16 18:32 UTC, KaHBrat commented
added the missing "this"

2020-07-17 06:25 UTC, TobiasMeissner2000 approved these changes

2020-07-17 06:26 UTC, merged